apiVersion: v1
kind: Service
metadata:
  name: ahch-to
  annotations:
    io.cilium/global-service: "true"
    io.cilium/portal: "true"
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: ahch-to