apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: ahch-to
nodes:
  - role: control-plane
networking:
  disableDefaultCNI: true
  ipFamily: ipv4
  podSubnet: 10.242.0.0/16
  kubeProxyMode: none
  serviceSubnet: 10.112.0.0/24
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
      endpoint = ["http://kind-registry:5000"]
