---
apiVersion: v1
kind: Pod
metadata:
  name: kylo-ren
  labels:
    org: first-order
spec:
  containers:
  - name: kylo-ren
    image: ${DOCKER_REGISTRY}/netcat-message:${DOCKER_TAG}
    env: 
    - name: MESSAGE
      value: "I'll show you the dark side"
    - name: PORT
      value: "80"
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
